[tool.poetry]
name = "cat"
version = "0.1.0"
description = ""
authors = ["artem <huaweitit0101@gmail.com>"]
license = "Copyright"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
